/* C Abstract Syntax Implementation generated by the BNF Converter. */

#include <stdio.h>
#include <stdlib.h>
#include "Absyn.h"


/********************   Prog    ********************/
Program make_Prog(ListStm p1)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog!\n");
        exit(1);
    }
    tmp->kind = is_Prog;
    tmp->u.prog_.liststm_ = p1;
    return tmp;
}/********************   ListStm    ********************/
ListStm make_ListStm(Stm p1, ListStm p2)
{
    ListStm tmp = (ListStm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListStm!\n");
        exit(1);
    }
    tmp->stm_ = p1;
    tmp->liststm_ = p2;
    return tmp;
}/********************   InitTex    ********************/
Stm make_InitTex(String p1, String p2, String p3)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating InitTex!\n");
        exit(1);
    }
    tmp->kind = is_InitTex;
    tmp->u.inittex_.string_1 = p1;
    tmp->u.inittex_.string_2 = p2;
    tmp->u.inittex_.string_3 = p3;
    return tmp;
}
/********************   OutTex    ********************/
Stm make_OutTex(Ident p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating OutTex!\n");
        exit(1);
    }
    tmp->kind = is_OutTex;
    tmp->u.outtex_.ident_ = p1;
    return tmp;
}
/********************   SOutTex    ********************/
Stm make_SOutTex(String p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating SOutTex!\n");
        exit(1);
    }
    tmp->kind = is_SOutTex;
    tmp->u.souttex_.string_ = p1;
    return tmp;
}
/********************   CloseTex    ********************/
Stm make_CloseTex()
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CloseTex!\n");
        exit(1);
    }
    tmp->kind = is_CloseTex;
    return tmp;
}
/********************   Redirect    ********************/
Stm make_Redirect()
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Redirect!\n");
        exit(1);
    }
    tmp->kind = is_Redirect;
    return tmp;
}
/********************   Print    ********************/
Stm make_Print(Ident p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Print!\n");
        exit(1);
    }
    tmp->kind = is_Print;
    tmp->u.print_.ident_ = p1;
    return tmp;
}
/********************   SPrint    ********************/
Stm make_SPrint(String p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating SPrint!\n");
        exit(1);
    }
    tmp->kind = is_SPrint;
    tmp->u.sprint_.string_ = p1;
    return tmp;
}
/********************   RPrint    ********************/
Stm make_RPrint(Row p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating RPrint!\n");
        exit(1);
    }
    tmp->kind = is_RPrint;
    tmp->u.rprint_.row_ = p1;
    return tmp;
}
/********************   PMat    ********************/
Stm make_PMat(Ident p1, ListRow p2)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating PMat!\n");
        exit(1);
    }
    tmp->kind = is_PMat;
    tmp->u.pmat_.ident_ = p1;
    tmp->u.pmat_.listrow_ = p2;
    return tmp;
}
/********************   RSwp    ********************/
Stm make_RSwp(Row p1, Row p2)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating RSwp!\n");
        exit(1);
    }
    tmp->kind = is_RSwp;
    tmp->u.rswp_.row_1 = p1;
    tmp->u.rswp_.row_2 = p2;
    return tmp;
}
/********************   RSet    ********************/
Stm make_RSet(Row p1, Row p2)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating RSet!\n");
        exit(1);
    }
    tmp->kind = is_RSet;
    tmp->u.rset_.row_1 = p1;
    tmp->u.rset_.row_2 = p2;
    return tmp;
}
/********************   RAss    ********************/
Stm make_RAss(Row p1, Row p2)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating RAss!\n");
        exit(1);
    }
    tmp->kind = is_RAss;
    tmp->u.rass_.row_1 = p1;
    tmp->u.rass_.row_2 = p2;
    return tmp;
}
/********************   Rref    ********************/
Stm make_Rref(Ident p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Rref!\n");
        exit(1);
    }
    tmp->kind = is_Rref;
    tmp->u.rref_.ident_ = p1;
    return tmp;
}
/********************   Ref    ********************/
Stm make_Ref(Ident p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Ref!\n");
        exit(1);
    }
    tmp->kind = is_Ref;
    tmp->u.ref_.ident_ = p1;
    return tmp;
}
/********************   AVar    ********************/
Stm make_AVar(Ident p1, Exp p2)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating AVar!\n");
        exit(1);
    }
    tmp->kind = is_AVar;
    tmp->u.avar_.ident_ = p1;
    tmp->u.avar_.exp_ = p2;
    return tmp;
}
/********************   CDoub    ********************/
Stm make_CDoub(Ident p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CDoub!\n");
        exit(1);
    }
    tmp->kind = is_CDoub;
    tmp->u.cdoub_.ident_ = p1;
    return tmp;
}
/********************   CInt    ********************/
Stm make_CInt(Ident p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CInt!\n");
        exit(1);
    }
    tmp->kind = is_CInt;
    tmp->u.cint_.ident_ = p1;
    return tmp;
}
/********************   Pause    ********************/
Stm make_Pause()
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Pause!\n");
        exit(1);
    }
    tmp->kind = is_Pause;
    return tmp;
}/********************   PRow    ********************/
Row make_PRow(ListExp p1)
{
    Row tmp = (Row) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating PRow!\n");
        exit(1);
    }
    tmp->kind = is_PRow;
    tmp->u.prow_.listexp_ = p1;
    return tmp;
}
/********************   RAdd    ********************/
Row make_RAdd(Row p1, Row p2)
{
    Row tmp = (Row) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating RAdd!\n");
        exit(1);
    }
    tmp->kind = is_RAdd;
    tmp->u.radd_.row_1 = p1;
    tmp->u.radd_.row_2 = p2;
    return tmp;
}
/********************   RSub    ********************/
Row make_RSub(Row p1, Row p2)
{
    Row tmp = (Row) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating RSub!\n");
        exit(1);
    }
    tmp->kind = is_RSub;
    tmp->u.rsub_.row_1 = p1;
    tmp->u.rsub_.row_2 = p2;
    return tmp;
}
/********************   RMul    ********************/
Row make_RMul(Exp p1, Row p2)
{
    Row tmp = (Row) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating RMul!\n");
        exit(1);
    }
    tmp->kind = is_RMul;
    tmp->u.rmul_.exp_ = p1;
    tmp->u.rmul_.row_ = p2;
    return tmp;
}
/********************   RDiv    ********************/
Row make_RDiv(Row p1, Exp p2)
{
    Row tmp = (Row) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating RDiv!\n");
        exit(1);
    }
    tmp->kind = is_RDiv;
    tmp->u.rdiv_.row_ = p1;
    tmp->u.rdiv_.exp_ = p2;
    return tmp;
}
/********************   RMul2    ********************/
Row make_RMul2(Row p1, Exp p2)
{
    Row tmp = (Row) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating RMul2!\n");
        exit(1);
    }
    tmp->kind = is_RMul2;
    tmp->u.rmul2_.row_ = p1;
    tmp->u.rmul2_.exp_ = p2;
    return tmp;
}
/********************   SMat    ********************/
Row make_SMat(Ident p1, Exp p2)
{
    Row tmp = (Row) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating SMat!\n");
        exit(1);
    }
    tmp->kind = is_SMat;
    tmp->u.smat_.ident_ = p1;
    tmp->u.smat_.exp_ = p2;
    return tmp;
}/********************   ListExp    ********************/
ListExp make_ListExp(Exp p1, ListExp p2)
{
    ListExp tmp = (ListExp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListExp!\n");
        exit(1);
    }
    tmp->exp_ = p1;
    tmp->listexp_ = p2;
    return tmp;
}/********************   ListRow    ********************/
ListRow make_ListRow(Row p1, ListRow p2)
{
    ListRow tmp = (ListRow) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListRow!\n");
        exit(1);
    }
    tmp->row_ = p1;
    tmp->listrow_ = p2;
    return tmp;
}/********************   EAdd    ********************/
Exp make_EAdd(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EAdd!\n");
        exit(1);
    }
    tmp->kind = is_EAdd;
    tmp->u.eadd_.exp_1 = p1;
    tmp->u.eadd_.exp_2 = p2;
    return tmp;
}
/********************   ESub    ********************/
Exp make_ESub(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ESub!\n");
        exit(1);
    }
    tmp->kind = is_ESub;
    tmp->u.esub_.exp_1 = p1;
    tmp->u.esub_.exp_2 = p2;
    return tmp;
}
/********************   EMul    ********************/
Exp make_EMul(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EMul!\n");
        exit(1);
    }
    tmp->kind = is_EMul;
    tmp->u.emul_.exp_1 = p1;
    tmp->u.emul_.exp_2 = p2;
    return tmp;
}
/********************   EDiv    ********************/
Exp make_EDiv(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EDiv!\n");
        exit(1);
    }
    tmp->kind = is_EDiv;
    tmp->u.ediv_.exp_1 = p1;
    tmp->u.ediv_.exp_2 = p2;
    return tmp;
}
/********************   ESInt    ********************/
Exp make_ESInt(SInteger p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ESInt!\n");
        exit(1);
    }
    tmp->kind = is_ESInt;
    tmp->u.esint_.sinteger_ = p1;
    return tmp;
}
/********************   EDob    ********************/
Exp make_EDob(Double p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EDob!\n");
        exit(1);
    }
    tmp->kind = is_EDob;
    tmp->u.edob_.double_ = p1;
    return tmp;
}
/********************   EIden    ********************/
Exp make_EIden(Ident p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EIden!\n");
        exit(1);
    }
    tmp->kind = is_EIden;
    tmp->u.eiden_.ident_ = p1;
    return tmp;
}
/********************   ConstE    ********************/
Exp make_ConstE()
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ConstE!\n");
        exit(1);
    }
    tmp->kind = is_ConstE;
    return tmp;
}
/********************   ConstPI    ********************/
Exp make_ConstPI()
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ConstPI!\n");
        exit(1);
    }
    tmp->kind = is_ConstPI;
    return tmp;
}
